카메라 권한 허용 후 카메라 시작
boostcampwm-2024/and04-Nature-Album pull request #69
Opened 2024-11-05 08:47 UTC by kim4152

# 진행 완료 리스트

✅ 메인 화면 UI 구현  

✅ 권한 허용 로직  

✅ 권한 허용 후 카메라 Intent  

---

- 권한 흐름
<img width="570" alt="스크린샷 2024-11-05 오후 5 44 45" src="https://github.com/user-attachments/assets/b8708691-38ef-4134-82be-bcef7ebc6c4f">

# 진행 사항 고민과 해결
권한 획득 로직을 MainActivity에서 구현하고 람다로 HomeScreen에 전달할지, 혹은 HomeScreen에서 LocalContext.current를 통해 직접 Context를 얻어 처리할지 고민했습니다.   
UI 역할만을 수행하도록 HomeScreen의 역할을 한정하기 위해, 전자의 방식을 최종 선택했습니다.

2024-11-05 09:00 UTC, yujin45 commented on app/src/main/java/com/and04/naturealbum/MainActivity.kt
> +        }
혹시 result 타입이 무엇인가요? 뒤에 :으로 명시해주시면 좋을 것 같습니다 😄

2024-11-05 09:00 UTC, yujin45 commented on app/src/main/java/com/and04/naturealbum/MainActivity.kt
> +            val hasPreviouslyDeniedPermission = deniedPermissions.any { permission: String ->
permission: String으로 통일하면 좋을 것 같습니다 👍🏻

2024-11-05 09:02 UTC, yujin45 commented on app/src/main/java/com/and04/naturealbum/MainActivity.kt
> +                        data = Uri.fromParts("package", packageName, null)
이 코드는 어떤 동작을 하나요? 잘 모르겠어서 질문드립니다!

2024-11-05 09:03 UTC, yujin45 commented on app/src/main/java/com/and04/naturealbum/MyDialog.kt
> +        },
자동완성 it 보다는 어떤 것인지 명시하는 변수명으로 작성하면 좋을 것 같습니다

2024-11-05 09:21 UTC, kimdoyun98 commented on app/src/main/java/com/and04/naturealbum/MainActivity.kt
> +            // display error state to the user
추후에 추가해야 하는 부분은 //TODO로 명확하게 표시해두는 것이 좋아보입니다.

2024-11-05 09:21 UTC, kimdoyun98 commented on app/src/main/java/com/and04/naturealbum/HomeViewModel.kt
> +    val dialogData: StateFlow<DialogData> = _dialogData
다이얼로그의 데이터를 ViewModel에서 관리하는 이유가 뭔가요?
HomeScreen에서 if문으로 비교하던데 궁금합니다.

2024-11-05 09:29 UTC, Jinhwan99 commented on app/build.gradle.kts
> +    implementation(libs.androidx.navigation.compose)
네비게이션 의존성 중복인것 같습니다

2024-11-05 09:34 UTC, kim4152 commented on app/src/main/java/com/and04/naturealbum/MainActivity.kt
> +                        data = Uri.fromParts("package", packageName, null)
(사용자가 끝까지 권한 허용을 하지 않으면) Intent로 설정에서 직접 권한을 허용하게끔 하는 동작입니다.

2024-11-05 09:35 UTC, kim4152 commented on app/build.gradle.kts
> +    implementation(libs.androidx.navigation.compose)
눈썰미가 좋으십니다. 수정하겠습니다!

2024-11-05 09:47 UTC, kimdoyun98 commented on app/src/main/java/com/and04/naturealbum/MainActivity.kt
>          enableEdgeToEdge()
컴포즈에서는 빼도 될 것 같습니다.

2024-11-05 09:55 UTC, kim4152 commented on app/src/main/java/com/and04/naturealbum/HomeViewModel.kt
> +    val dialogData: StateFlow<DialogData> = _dialogData
현재 MainActivity 에서 권한 로직을 담당하고 있고, HomeScreen 에서는 사용자에게 보여줄 Dialog(UI)를 담당하고 있습니다.
그래서 MainActivity에서 사용자의 입력에 따라 HomeScreen의 Dialog를 띄우기 위해 중간에 뷰모델을 하나 뒀습니다.

2024-11-05 09:56 UTC, kim4152 commented on app/src/main/java/com/and04/naturealbum/MainActivity.kt
>          enableEdgeToEdge()
영상 공유 감사합니다

2024-11-06 01:16 UTC, kimdoyun98 commented on app/src/main/java/com/and04/naturealbum/savephoto/SavePhotoScreen.kt
> +                    text = "저장",
하드 코딩 수정 부탁드립니다.

2024-11-06 01:20 UTC, yujin45 requested changes

2024-11-06 01:20 UTC, yujin45 commented on app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
> +}
luminance 관련하여 이미 존재하므로 함수를 사용하면 좋을 것 같습니다. 
아래를 참고해주세요!
```
import androidx.compose.ui.graphics.luminance
Composable
fun CustomLabel(
    text: String,
    backgroundColor: Color,
    modifier: Modifier = Modifier
) {
    val calculatedTextColor = if (backgroundColor.luminance() > 0.5f) Color.Black else Color.White

    Box(
        contentAlignment = Alignment.Center,
        modifier = modifier
            .background(color = backgroundColor, shape = CircleShape)
            .fillMaxWidth(0.8f)
    ) {
        Text(
            text = text,
            color = calculatedTextColor,
            style = AppTypography.labelMedium,
            fontWeight = FontWeight.SemiBold
        )
    }
}

```

2024-11-06 01:20 UTC, Jinhwan99 commented on app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
> +    model: Any?,
Any? 타입에 대한 처리가 잘 안된것 같습니다

2024-11-06 01:20 UTC, Jinhwan99 commented on app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
description, role 지정하기

2024-11-06 01:23 UTC, Jinhwan99 commented on app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
> +}
감사합니다!!!!

2024-11-06 01:48 UTC, merged

2024-11-06 01:49 UTC, yujin45 commented on app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
추후 적용하면 좋을 것 같습니다!

2024-11-06 01:49 UTC, yujin45 commented on app/src/main/java/com/and04/naturealbum/ui/savephoto/SavePhotoScreen.kt
> +    model: Any?,
이후 정해지면 수정해보도록 하죠

2024-11-06 02:39 UTC, Jinhwan99 commented on app/src/main/java/com/and04/naturealbum/savephoto/SavePhotoScreen.kt
> +                    text = "저장",
업데이트 했습니다!!!